Part4
Svelte-Society-Fr/kit pull request #18
Opened 2023-10-11 07:11 UTC by bleucitron

2023-10-16 16:08 UTC, Ennoriel requested changes

2023-10-16 16:08 UTC, Ennoriel commented on documentation/docs/30-advanced/10-advanced-routing.md
> +Les paramètres de reste vous permettent également d'afficher des pages 404s personnalisées. Étant données ces routes...
```suggestion
Les paramètres de reste vous permettent également d'afficher des pages 404 personnalisées. Étant données ces routes...
```

2023-10-16 16:08 UTC, Ennoriel commented on documentation/docs/30-advanced/10-advanced-routing.md
> +- Les paramètres `[[optional]]` and `[...rest]` sont ignorés à moins qu'ils soient tout à la fin de la route, auquel cas ils sont traitées avec la priorité la plus faible. En d'autres mots `x/[[y]]/z
```suggestion
- Les paramètres `[[optional]]` et `[...rest]` sont ignorés à moins qu'ils soient tout à la fin de la route, auquel cas ils sont traitées avec la priorité la plus faible. En d'autres mots `x/[[y]]/z` est traité de manière équivalente à `x/z` d'un point de vue du tri
```

2023-10-16 16:08 UTC, Ennoriel commented on documentation/docs/30-advanced/10-advanced-routing.md
> +Certains caractères ne peuvent pas être utilisés pas le système de fichiers – `/` sur Linux et Mac, `\ / : * ? " < > |` sur Windows. Les caractères `#` et `%` ont un sens particulier dans les URLs, e
```suggestion
Certains caractères ne peuvent pas être utilisés pas le système de fichiers – `/` sur Linux et Mac, `\ / : * ? " < > |` sur Windows. Les caractères `#` et `%` ont un sens particulier dans les URLs, et les caractères `[ ] ( )` ont un sens particulier pour SvelteKit, ce qui implique qu'ils ne peuvent pas non plus être utilisés directement comme morceau de votre route.
```
je ne suis pas sur de moi ;)

2023-10-16 16:08 UTC, Ennoriel commented on documentation/docs/30-advanced/10-advanced-routing.md
> +Les pages peuvent s'échapper de la hiérarchie de <span class="vo">[layout](PUBLIC_SVELTE_SITE_URL/docs/web#layout)</span> courante route par route. Supposez que nous ayons une route `/item/[id]/embed
```suggestion
Les pages peuvent s'échapper de la hiérarchie de <span class="vo">[layout](PUBLIC_SVELTE_SITE_URL/docs/web#layout)</span> courante, route par route. Supposez que nous ayons une route `/item/[id]/embed` dans le groupe `(app)` de l'exemple précédent :
```

2023-10-16 16:08 UTC, Ennoriel commented on documentation/docs/30-advanced/20-hooks.md
> +Cette fonction est exécutée à chaque fois que le serveur SvelteKit reçoit une [requête](web-standards#apis-fetch-request) – que cette requête ait lieu pendant que l'application est en service ou pend
```suggestion
Cette fonction est exécutée à chaque fois que le serveur SvelteKit reçoit une [requête](web-standards#apis-fetch-request) – que cette requête ait lieu pendant que l'application est en service ou pendant le processus de [prérendu](page-options#prerender) – et en détermine la [réponse](web-standards#apis-fetch-response). La fonction reçoit un objet `event` représentant la requête et une fonction appelée `resolve`, qui rend la route et génère une `Response`. Cela vous permet de modifier les <span class="vo">[headers](PUBLIC_SVELTE_SITE_URL/docs/web#header)</span> ou le <span class="vo">[body](PUBLIC_SVELTE_SITE_URL/docs/web#body)</span> de réponse, ou de complètement contourner SvelteKit (pour implémenter des routes programmatiquement par exemple).
```
c'est quoi les bodies ? une requête à plusieurs contenus ?!

2023-10-16 16:08 UTC, Ennoriel commented on documentation/docs/30-advanced/20-hooks.md
> +- vous pouvez générer une représentation de l'erreur que vous afficher aux utilisateurs et utilisatrices, en y enlevant les informations sensibles comme les messages ou les <span class="vo">[stack tr
```suggestion
- vous pouvez générer une représentation de l'erreur que vous affichez aux utilisateurs et utilisatrices, en y enlevant les informations sensibles comme les messages ou les <span class="vo">[stack traces](PUBLIC_SVELTE_SITE_URL/docs/development#stack-trace)</span>. La valeur renvoyée devient la valeur de `$page.error`. Elle vaut par défaut `{ message: 'Not Found' }` dans le cas d'une erreur 404 (vous pouvez les détecter grâce à `event.route.id` qui vaudra `null`) et `{ message: 'Internal Error' }` pour tout le reste. Pour y ajouter du typage, vous pouvez personnaliser la forme de l'objet en déclarant l'interface `App.Error` (qui doit inclure `message: string`, pour garantir le comportement par défaut).
```

2023-10-16 16:08 UTC, Ennoriel commented on documentation/docs/30-advanced/25-errors.md
> +Vous pouvez ajouter des propriétés supplémentaires, comme `code` ou un `id` de suivi, comme montré dans les exemples ci-dessous. (Lorsque vous utilisez TypeScript, ceci requiert que vous redéfinissie
```suggestion
Vous pouvez ajouter des propriétés supplémentaires, comme un `code` ou un `id` de suivi, comme montré dans les exemples ci-dessous. (Lorsque vous utilisez TypeScript, ceci requiert que vous redéfinissiez le type `Error` comme décrit dans la section sur le [typage](errors#typage)).
```

2023-10-16 16:08 UTC, Ennoriel commented on documentation/docs/30-advanced/25-errors.md
> +Ceci dit à SvelteKit de définir le statut de réponse à 404 et de rendre un composant [`+error.svelte`](routing#error), où `$page.error` est un objet fourni comme second argument à `error(...)`.
```suggestion
Ceci indique à SvelteKit de définir le statut de réponse à 404 et de rendre un composant [`+error.svelte`](routing#error), où `$page.error` est un objet fourni comme second argument à `error(...)`.
```

2023-10-16 16:08 UTC, Ennoriel commented on documentation/docs/30-advanced/25-errors.md
> +Une erreur _inattendue_ est toute autre exception qui se produit pendant qu'une requête est traitée. Puisqu'ils peuvent contenir des informations sensibles, les messages des erreurs inattendues et le
```suggestion
Une erreur _inattendue_ est toute autre exception qui se produit pendant qu'une requête est traitée. Puisqu'ils peuvent contenir des informations sensibles, les messages des erreurs inattendues et leure <span class="vo">[stack trace](PUBLIC_SVELTE_SITE_URL/docs/development#stack-trace)</span> ne sont pas exposés aux utilisateurs et utilisatrices.
```
je ne suis pas sûr non plus

2023-10-16 19:42 UTC, bleucitron commented on documentation/docs/30-advanced/10-advanced-routing.md
> +Certains caractères ne peuvent pas être utilisés pas le système de fichiers – `/` sur Linux et Mac, `\ / : * ? " < > |` sur Windows. Les caractères `#` et `%` ont un sens particulier dans les URLs, e
"**ils** ne peuvent pas être utilisés", c'est bien du pluriel

2023-10-16 19:44 UTC, bleucitron commented on documentation/docs/30-advanced/20-hooks.md
> +Cette fonction est exécutée à chaque fois que le serveur SvelteKit reçoit une [requête](web-standards#apis-fetch-request) – que cette requête ait lieu pendant que l'application est en service ou pend
Non, c'est plus "les bodys en général" des réponses. Mais on peut mettre au singulier si tu préfères

2023-10-16 19:44 UTC, bleucitron commented on documentation/docs/30-advanced/25-errors.md
> +Une erreur _inattendue_ est toute autre exception qui se produit pendant qu'une requête est traitée. Puisqu'ils peuvent contenir des informations sensibles, les messages des erreurs inattendues et le
Non, "leure" ça n'existe pas :)

2023-10-18 05:58 UTC, Ennoriel commented on documentation/docs/30-advanced/20-hooks.md
> +Cette fonction est exécutée à chaque fois que le serveur SvelteKit reçoit une [requête](web-standards#apis-fetch-request) – que cette requête ait lieu pendant que l'application est en service ou pend
oui, ça fait moins bizarre je trouve

2023-10-18 06:17 UTC, Ennoriel requested changes

2023-10-18 06:17 UTC, Ennoriel commented on documentation/docs/30-advanced/30-link-options.md
> +'utilisateur ou l'utilisatrice clique sur un lien dont le `href` "appartient" à votre application (plutôt que de pointer vers un site extérieur par exemple), alors SvelteKit va naviguer vers la nouve
```suggestion
Dans une application SvelteKit, les éléments `<a>` sont utilisés pour naviguer entre les différentes routes de votre application, plutôt qu'avec des composants `<Link>` spécifiques au <span class="vo">[framework](PUBLIC_SVELTE_SITE_URL/docs/web#framework)</span>. Si l'utilisateur ou l'utilisatrice clique sur un lien dontl l'attribut `href` "appartient" à votre application (plutôt que de pointer vers un site extérieur par exemple), alors SvelteKit va naviguer vers la nouvelle page en important son code puis en appelant toute fonction `load` nécessaire pour le chargement des données de la page.
```

2023-10-18 06:17 UTC, Ennoriel commented on documentation/docs/30-advanced/30-link-options.md
> +Avant que le navigateur se rende compte qu'un lien a été cliqué, nous pouvons détecter que le lien est en train d'être survolé (sur <span class="vo">[desktop](PUBLIC_SVELTE_SITE_URL/docs/web#desktop)
```suggestion
Avant que le navigateur se rende compte qu'un lien n'ait été cliqué, nous pouvons détecter que le lien est en train d'être survolé (sur ordinateur) ou qu'un évènement `touchstart` ou `mousedown` ait été déclenché. Dans les deux cas, nous pouvons supposer qu'un évènement `click` sur ce lien est probable.
```
desktop => ordinateur non ?

2023-10-18 06:17 UTC, Ennoriel commented on documentation/docs/30-advanced/30-link-options.md
> +Comme pour `data-sveltekit-preload-data`, cet attribut sera ignoré si l'usage réduit de données a été activé.
c'est quoi l'usage réduit de données ? C'est un paramètre du navigateur ??

2023-10-18 06:17 UTC, Ennoriel commented on documentation/docs/30-advanced/30-link-options.md
> +...va permettre à l'élément ayant le focus de le garder après la navigation. Il est en général recommandé d'éviter d'utiliser cet attribut sur des liens, puisque l'élément ayant le focus serait la ba
```suggestion
...va permettre à l'élément ayant le focus de le garder après la navigation. Il est en général recommandé d'éviter d'utiliser cet attribut sur des liens, puisque l'élément ayant le focus serait la balise `<a>` (et non un autre élément ayant eu précédemment le focus), et les lecteurs d'écran et les personnes utilisant des technologies d'assistance s'attendent à voir le focus se déplacer après une navigation. De plus, vous ne devriez utiliser cet attribut que sur des éléments qui existent toujours après la navigation, sinon, le focus sera perdu, entraînant de la confusion pour les personnes utilisant des technologies d'assistance.
```

2023-10-18 06:17 UTC, Ennoriel commented on documentation/docs/30-advanced/50-server-only-modules.md
> +À chaque que du code prévu pour être affiché au public importe du code réservé au serveur (directement ou indirectement)...
```suggestion
À chaque fois que du code prévu pour être affiché au public importe du code réservé au serveur (directement ou indirectement)...
```

2023-10-18 06:44 UTC, bleucitron commented on documentation/docs/30-advanced/30-link-options.md
> +Comme pour `data-sveltekit-preload-data`, cet attribut sera ignoré si l'usage réduit de données a été activé.
J'ai jamais utilisé, mais sur mobile Chrome propose ça. Peut-être sur d'autres plate-formes

2023-10-19 04:56 UTC, Ennoriel commented on documentation/docs/30-advanced/30-link-options.md
> +Comme pour `data-sveltekit-preload-data`, cet attribut sera ignoré si l'usage réduit de données a été activé.
```suggestion
Comme pour `data-sveltekit-preload-data`, cet attribut sera ignoré si l'usage réduit de données a été activé par l'utilisateur.
```

2023-10-19 05:16 UTC, Ennoriel requested changes

2023-10-19 05:16 UTC, Ennoriel commented on documentation/docs/30-advanced/70-packaging.md
> +Lorsque vous créez une application, le contenu de `src/routes` est ce que vous affichez au public ; le dossier [`src/lib`](modules#$lib) contient la libraire interne de votre application.
```suggestion
Lorsque vous créez une _application_, le contenu de `src/routes` correspond à ce que vous affichez au public ; le dossier [`src/lib`](modules#$lib) contient la libraire interne de votre application.
```

2023-10-19 05:16 UTC, Ennoriel commented on documentation/docs/30-advanced/70-packaging.md
> +Une librairie de composants a exactement la même structure qu'une application SvelteKit, sauf c'est le dossier `src/lib` qui est ce que va consommer le public, et votre `package.json` sert à publier
```suggestion
Une _librairie de composants_ a exactement la même structure qu'une application SvelteKit, sauf que c'est le dossier `src/lib` qui sera consommé par le public, et votre `package.json` sert à publier le paquet. Le dossier `src/routes` peut être une documentation ou un site de démo qui accompagne la librairie, ou bien simplement un bac à sable que vous utilisez pendant vos développements.
```

2023-10-19 05:16 UTC, Ennoriel commented on documentation/docs/30-advanced/70-packaging.md
> +Celle indique aux <span class="vo">[bundlers](PUBLIC_SVELTE_SITE_URL/docs/development#bundler-packager)</span> et autres outillages que votre paquet n'a qu'un seul point d'entrée, la racine, et que t
```suggestion
Cela indique aux <span class="vo">[bundlers](PUBLIC_SVELTE_SITE_URL/docs/development#bundler-packager)</span> et autres outillages que votre paquet n'a qu'un seul point d'entrée, la racine, et que tout le reste doit être importé via ce point d'entrée, de cette manière :
```

2023-10-19 05:16 UTC, Ennoriel commented on documentation/docs/30-advanced/70-packaging.md
> +> Les versions antérieures de `@sveltejs/package` incluaient également un export `package.json`. Celui-ci ne fait plus partie du <span class="vo">[template](PUBLIC_SVELTE_SITE_URL/docs/development#te
```suggestion
> Les versions antérieures de `@sveltejs/package` incluaient également un export `package.json`. Celui-ci ne fait plus partie du <span class="vo">[template](PUBLIC_SVELTE_SITE_URL/docs/development#template)</span> car les outillages sont maintenant prévus pour fonctionner même si `package.json` n'est pas explicitement exporté.
```

2023-10-19 05:16 UTC, Ennoriel commented on documentation/docs/30-advanced/70-packaging.md
> +En général, chaque propriété de le dictionnaire d'exports est le chemin qu'un utilisateur ou utilisatrice doit utiliser pour importer quelque chose depuis votre paquet, et la valeur est le chemin ver
```suggestion
En général, chaque propriété du dictionnaire d'exports est le chemin qu'un utilisateur ou utilisatrice doit utiliser pour importer quelque chose depuis votre paquet, et la valeur est le chemin vers le fichier qui sera importé ou un dictionnaire de conditions d'exports qui lui-même contient ces chemins de fichiers.
```

2023-10-19 05:16 UTC, Ennoriel commented on documentation/docs/30-advanced/70-packaging.md
> +Vous recommandons d'éviter d'utiliser des [modules spécifiques à SvelteKit](modules) comme `$app` dans votre librairie à moins que celle-ci soit uniquement conçue être utilisée pour des projets Svelt
```suggestion
Nous recommandons d'éviter d'utiliser des [modules spécifiques à SvelteKit](modules) comme `$app` dans votre librairie à moins que celle-ci soit uniquement conçue être utilisée pour des projets SvelteKit. Par exemple, plutôt que d'utiliser `import { browser } from '$app/environment'`, vous pourriez utiliser `import { BROWSER } from 'esm-env'` ([voir la documentation de `esm-env`](https://github.com/benmccann/esm-env) (en anglais)). Vous pouvez peut-être également fournir l'URL courante ou une action de navigation en tant que <span class="vo">[prop](PUBLIC_SVELTE_SITE_URL/docs/sveltejs#prop)</span> plutôt que de dépendre directement de `$app/stores`, `$app/navigation`, etc. Écrire votre librairie de façon plus générique vous permettra également de mettre en place plus facilement des outils de test, des sites de démos, ou autres.
```

2023-10-19 05:16 UTC, Ennoriel commented on documentation/docs/30-advanced/70-packaging.md
> +Tout import d'un fichier relatif doit être entièrement précisé, en adhérant à l'algorithme ESM de Node. Cela implique que pour un fichier tel que `src/lib/something/index.js`, vous devez inclure le n
```suggestion
Tout import d'un fichier relatif doit être entièrement précisé, en respectant l'algorithme ESM de Node. Cela implique que pour un fichier tel que `src/lib/something/index.js`, vous devez inclure le nom du fichier ainsi que son extension :
```

2023-10-20 08:00 UTC, merged