Part1
Svelte-Society-Fr/kit pull request #2
Opened 2023-09-14 16:23 UTC by bleucitron

Je me rends compte maintenant (je le savais, mais j'avais oublié), qu'il y a un glossaire dans la doc de SvelteKit, qui inclut notamment les items SSR, CSR, etc...

On fait quoi ?
- on laisse ces entrées dans le glossaire de la doc de Svelte aussi
- on sépare, ce qui fait 2 glossaires à 2 endroits différents

J'avoue, je n'ai pas de réponse parfaitement satisfaisante...

2023-09-15 19:29 UTC, Ennoriel approved these changes

2023-09-19 19:39 UTC, Ennoriel requested changes

2023-09-19 19:39 UTC, Ennoriel commented on documentation/docs/10-getting-started/20-creating-a-project.md
> +La façon la plus simple de commencer à construire une application SvelteKit est d'utiliser `npm create` :
```suggestion
La façon la plus simple de commencer une application SvelteKit est d'utiliser `npm create` :
```
ça s'éloigne de la traduction littérale mais ça fait bizarre

2023-09-19 19:39 UTC, Ennoriel commented on documentation/docs/10-getting-started/20-creating-a-project.md
> +La première commande va préparer un nouveau projet dans le dossier `my-app`, en vous proposant d'utiliser de l'outillage de base comme TypeScript.
```suggestion
La première commande va générer un nouveau projet dans le dossier `my-app`, en vous proposant d'utiliser de l'outillage de base comme TypeScript.
```

2023-09-19 19:39 UTC, Ennoriel commented on documentation/docs/10-getting-started/30-project-structure.md
> +│ │ │ └ [vos fichiers spécifiques serveur]
```suggestion
│ │ │ └ [vos fichiers spécifiques serveurs]
```
? ou alors du serveur ?

2023-09-19 19:39 UTC, Ennoriel commented on documentation/docs/10-getting-started/30-project-structure.md
> +  - `%sveltekit.head%` — les éléments `<link>` et `<script>` requis par votre application, plus tout contenu `<svelte:head>` éventuel
```suggestion
  - `%sveltekit.head%` — les éléments `<link>` et `<script>` requis par votre application, ainsi que le contenu `<svelte:head>` éventuel
```

2023-09-19 19:39 UTC, Ennoriel commented on documentation/docs/30-advanced/20-hooks.md
> +This function runs every time the SvelteKit server receives a [request](web-standards#apis-fetch-response) — whether that happens while the app is running, or during [prerendering](page-options#prere
c'est volontaire je suppose, tu as copié/remplacé les liens partout ?

2023-09-19 19:39 UTC, Ennoriel commented on sites/kit.svelte.dev/src/routes/home/Features.svelte
> +				application ou une seule page. Utilisez un <strong>routing côté client</strong> accessible
```suggestion
				application ou seulement une seule page. Utilisez un <strong>routeur côté client</strong> accessible
```
je crois qu'on a mis routing partout mais je préfeur routeur :s

2023-09-19 19:39 UTC, Ennoriel commented on sites/kit.svelte.dev/src/routes/home/Features.svelte
> +				la même page. Ajoutez des service workers pour le support <strong>hors ligne</strong>.
```suggestion
				la même page. Ajoutez des services workers pour le support <strong>hors ligne</strong>.
```

2023-09-19 19:39 UTC, Ennoriel commented on sites/kit.svelte.dev/src/routes/home/Features.svelte
> +				des UIs complexes à l'aide d'un système puissant de routes basé sur votre arborescence de
```suggestion
				des UI complexes à l'aide d'un système puissant de routes basé sur votre arborescence de
```

2023-09-19 19:39 UTC, Ennoriel commented on sites/kit.svelte.dev/src/routes/home/Features.svelte
> +				fichiers Des layouts imbriqués ? Évidemment. Apprenez les <strong>standards du web</strong>
```suggestion
				fichiers. Des layouts imbriqués ? Évidemment. Apprenez les <strong>standards du web</strong>
```

2023-09-19 19:39 UTC, Ennoriel commented on sites/kit.svelte.dev/src/routes/home/subtitles.vtt
> + et facile que tout ce que l'on connu depuis longtemps.
```suggestion
 et plus facile que tout ce que l'on a connu depuis longtemps.
```

2023-09-19 19:39 UTC, Ennoriel commented on sites/kit.svelte.dev/src/routes/home/subtitles.vtt
> + JavaScript, et CSS basiques.
```suggestion
 du JavaScript, et du CSS basiques.
```

2023-09-19 19:39 UTC, Ennoriel commented on sites/kit.svelte.dev/src/routes/home/subtitles.vtt
> + JavaScript les plus utilisés.
```suggestion
 JavaScript utilisés.
```

2023-09-19 19:39 UTC, Ennoriel commented on sites/kit.svelte.dev/src/routes/home/subtitles.vtt
> + et je pense qu'en ça Svelte a un avantage incroyable.
```suggestion
 et je pense qu'en ça, Svelte a un avantage incroyable.
```

2023-09-19 20:53 UTC, bleucitron commented on documentation/docs/10-getting-started/30-project-structure.md
> +│ │ │ └ [vos fichiers spécifiques serveur]
au singulier plutot

2023-09-19 20:55 UTC, bleucitron commented on documentation/docs/30-advanced/20-hooks.md
> +This function runs every time the SvelteKit server receives a [request](web-standards#apis-fetch-response) — whether that happens while the app is running, or during [prerendering](page-options#prere
ici je pense que c'est une erreur d'avoir `response` pour le lien de request

2023-09-20 10:31 UTC, Ennoriel commented on documentation/docs/10-getting-started/30-project-structure.md
> +│ │ │ └ [vos fichiers spécifiques serveur]
```suggestion
│ │ │ └ [vos fichiers spécifiques de serveur]
```

2023-09-20 11:52 UTC, merged