Part 7
Svelte-Society-Fr/kit pull request #31
Opened 2023-10-31 17:49 UTC by bleucitron

2023-11-03 01:12 UTC, Ennoriel requested changes

2023-11-03 01:12 UTC, Ennoriel commented on documentation/docs/60-appendix/01-faq.md
> +title: Foire À Questions
```suggestion
title: Foire aux questions
```

2023-11-03 01:12 UTC, Ennoriel commented on documentation/docs/60-appendix/01-faq.md
> +Merci de consulter [la FÀQ de Svelte](PUBLIC_SVELTE_SITE_URL/faq) ainsi que la [FÀQ de `vite-plugin-svelte`](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md) (en anglais) pour vo
```suggestion
Merci de consulter [la FAQ de Svelte](PUBLIC_SVELTE_SITE_URL/faq) ainsi que la [FAQ de `vite-plugin-svelte`](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md) (en anglais) pour vos questions relatives à ces librairies.
```

2023-11-03 01:12 UTC, Ennoriel commented on documentation/docs/60-appendix/01-faq.md
> +- Applications web <span class='vo'>[serverless](PUBLIC_SVELTE_SITE_URL/docs/web#serverless)</span> avec des fonctions de chargement sur le serveur et des <span class='vo'>[APIs](PUBLIC_SVELTE_SITE_U
```suggestion
- Applications web <span class='vo'>[serverless](PUBLIC_SVELTE_SITE_URL/docs/web#serverless)</span> avec des fonctions de chargement sur le serveur et des <span class='vo'>[API](PUBLIC_SVELTE_SITE_URL/docs/development#api)</span> déployées en tant que fonctions distantes. Voir la section [Déploiements sans configuration](/docs/adapter-auto) pour plus d'infos sur les options de déploiement disponibles.
```

Je ne sais pas si tu as corrigé ailleurs finalement. Pour moi, les acronymes ne prennent pas de "s" en français

2023-11-03 01:12 UTC, Ennoriel commented on documentation/docs/60-appendix/01-faq.md
> +Il est également possible d'écrire des adaptateurs personnalisés ou de se servir des adapatateurs de la communauté pour déployer SvelteKit sur plus de plateformes tels que des environnements serveur
```suggestion
Il est également possible d'écrire des adaptateurs personnalisés ou de se servir des adapatateurs de la communauté pour déployer SvelteKit sur plus de plateformes tels que des environnements serveurs spécialisés, des extensions de navigateur ou des applications natives. Voir la section [Intégrations](./integrations) pour plus d'exemples.
```
?

2023-11-03 01:12 UTC, Ennoriel commented on documentation/docs/60-appendix/01-faq.md
> +Vous ne pouvez pas importer directement des fichiers <span class='vo'>[JSON](PUBLIC_SVELTE_SITE_URL/docs/web#json)</span>, puisque SvelteKit attend que le fichier [`svelte.config.js`](./configuration
```suggestion
Vous ne pouvez pas importer directement des fichiers <span class='vo'>[JSON](PUBLIC_SVELTE_SITE_URL/docs/web#json)</span>, puisque SvelteKit attend que le fichier [`svelte.config.js`](./configuration) soit un module ECMAScript. Si vous souhaitez inclure la version de votre application ou toute autre information de votre fichier `package.json` dans votre application, vous pouvez charger le JSON de cette manière :
```

2023-11-03 01:12 UTC, Ennoriel commented on documentation/docs/60-appendix/01-faq.md
> +Si la librairie que vous souhaitez utiliser n'a pas d'effets de bord, vous pouvez aussi l'importer de manière statique, elle sera alors retirée lors de la compilation (grâce au <span class='vo'>[tree
```suggestion
Si la librairie que vous souhaitez utiliser n'a pas d'effet de bord, vous pouvez aussi l'importer de manière statique, elle sera alors retirée lors de la compilation (grâce au <span class='vo'>[tree shaking](PUBLIC_SVELTE_SITE_URL/docs/development#tree-shaking)</span>) du code serveur compilé dans lequel `onMount` est automatiquement remplacé par une fonction inerte :
```

2023-11-03 07:28 UTC, bleucitron commented on documentation/docs/60-appendix/01-faq.md
> +- Applications web <span class='vo'>[serverless](PUBLIC_SVELTE_SITE_URL/docs/web#serverless)</span> avec des fonctions de chargement sur le serveur et des <span class='vo'>[APIs](PUBLIC_SVELTE_SITE_U
Il semblerait que la réponse soit entre les deux : https://www.dictionnaire-academie.fr/article/QDL079.

De mon point de vue, "API" est rentré dans le lexique courant, et devrait s'accorder. Mais je suis ok de le laisser invariant.

2023-11-03 07:29 UTC, bleucitron commented on documentation/docs/60-appendix/01-faq.md
> +Il est également possible d'écrire des adaptateurs personnalisés ou de se servir des adapatateurs de la communauté pour déployer SvelteKit sur plus de plateformes tels que des environnements serveur
Hm, pour moi c'est un raccourci pour "de type serveur", donc ça ne devrait pas. Il me semble d'ailleurs que qd on parlait des fonctions `load` de serveur, on écrivait "fonctions `load` serveur`.

2023-11-03 07:30 UTC, bleucitron commented on documentation/docs/60-appendix/01-faq.md
> +Vous ne pouvez pas importer directement des fichiers <span class='vo'>[JSON](PUBLIC_SVELTE_SITE_URL/docs/web#json)</span>, puisque SvelteKit attend que le fichier [`svelte.config.js`](./configuration
```suggestion
Vous ne pouvez pas importer directement des fichiers <span class='vo'>[JSON](PUBLIC_SVELTE_SITE_URL/docs/web#json)</span>, puisque SvelteKit attend que le fichier [`svelte.config.js`](./configuration) soit un module ECMAScript. Si vous souhaitez inclure le numéro de version de votre application ou toute autre information de votre fichier `package.json` dans votre application, vous pouvez charger le JSON de cette manière :
```

2023-11-03 19:54 UTC, Ennoriel requested changes

2023-11-03 19:54 UTC, Ennoriel commented on documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md
> +Lorsque vous déployez sur des <span class="vo">[workers](PUBLIC_SVELTE_SITE_URL/docs/development#worker)</span>, le serveur généré par SvelteKit est compilé en un seul fichier. Wrangler échouera à pu
```suggestion
Lorsque vous déployez sur des <span class="vo">[workers](PUBLIC_SVELTE_SITE_URL/docs/development#worker)</span>, le serveur généré par SvelteKit est compilé en un seul fichier. Wrangler échouera à publier votre worker s'il excède la [limite de taille](https://developers.cloudflare.com/workers/platform/limits/#worker-size) après minification. Vous ne devriez normalement pas dépasser cette limite, mais certaines grosses librairies peuvent vous faire rencontrer ce problème. Dans ce cas, essayez de réduire la taille de votre worker en important ce type de librairie uniquement côté client. Lire la [FAQ](./faq#comment-utiliser-x-avec-sveltekit-comment-utiliser-une-librairie-r-serv-e-au-client-qui-d-pend-de-document-ou-de-window) pour plus d'informations.
```

2023-11-04 08:33 UTC, Ennoriel commented on documentation/docs/60-appendix/01-faq.md
> +- Applications web <span class='vo'>[serverless](PUBLIC_SVELTE_SITE_URL/docs/web#serverless)</span> avec des fonctions de chargement sur le serveur et des <span class='vo'>[APIs](PUBLIC_SVELTE_SITE_U
mais dans ce cas, on le passe en  minuscules ;)

2023-11-04 08:33 UTC, Ennoriel commented on documentation/docs/60-appendix/01-faq.md
> +Il est également possible d'écrire des adaptateurs personnalisés ou de se servir des adapatateurs de la communauté pour déployer SvelteKit sur plus de plateformes tels que des environnements serveur
ça me va

2023-11-04 08:42 UTC, Ennoriel requested changes

2023-11-04 08:42 UTC, Ennoriel commented on documentation/docs/60-appendix/05-integrations.md
> +## FÀQ des intégrations
```suggestion
## FAQ des intégrations
```

2023-11-04 08:42 UTC, Ennoriel commented on documentation/docs/60-appendix/05-integrations.md
> +La FÀQ de SvelteKit a une section [Comment utiliser X avec SvelteKit](./faq#comment-utiliser-x-avec-sveltekit), qui peut vous aider si vous avez encore des questions.
```suggestion
La FAQ de SvelteKit a une section [Comment utiliser X avec SvelteKit](./faq#comment-utiliser-x-avec-sveltekit), qui peut vous aider si vous avez encore des questions.
```

2023-11-04 08:42 UTC, Ennoriel commented on documentation/docs/60-appendix/20-additional-resources.md
> +## FÀQs
```suggestion
## FAQ
```

2023-11-04 08:42 UTC, Ennoriel commented on documentation/docs/60-appendix/20-additional-resources.md
> +Merci de vous rendre sur [la FÀQ de SvelteKit](../faq) pour trouver des astuces ainsi que des solutions à des problèmes communs.
```suggestion
Vous trouverez des astuces et des solutions aux problèmes communs sur [la FAQ de SvelteKit](../faq).
```

2023-11-04 08:42 UTC, Ennoriel commented on documentation/docs/60-appendix/20-additional-resources.md
> +[La FÀQ de Svelte](PUBLIC_SVELTE_SITE_URL/faq) et celle de [`vite-plugin-svelte`](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md) (en anglais) peuvent également être utiles pour
```suggestion
[La FAQ de Svelte](PUBLIC_SVELTE_SITE_URL/faq) et celle de [`vite-plugin-svelte`](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md) (en anglais) peuvent également être utiles pour des questions relatives à ces librairies.
```

2023-11-04 08:42 UTC, Ennoriel commented on documentation/docs/60-appendix/20-additional-resources.md
> +Vous pouvez demander de l'aide sur le [serveur Discord officiel](https://svelte.dev/chat) ou sur le [serveur Discord francophone](PUBLIC_SVELTE_SITE_URL/chat), ainsi que sur [StackOverflow](https://s
```suggestion
Vous pouvez demander de l'aide sur le [serveur Discord officiel](https://svelte.dev/chat) ou sur le [serveur Discord francophone](PUBLIC_SVELTE_SITE_URL/chat), ainsi que sur [StackOverflow](https://stackoverflow.com/questions/tagged/sveltekit). Merci de d'abord chercher des informations sur votre problème dans la FAQ, sur Google, ou tout autre moteur de recherche, gestionnaire de tickets ou historique Discord afin de rester dans le respect du temps d'autrui. Il y a beaucoup plus de personnes qui posent des questions que de personnes qui y répondent, vous aiderez ainsi la communauté à se développer de manière fluide.
```

2023-11-05 20:32 UTC, Ennoriel requested changes

2023-11-05 20:32 UTC, Ennoriel commented on documentation/docs/60-appendix/30-glossary.md
> +Par défaut, lorsque vous naviguez vers une nouvelle page (en cliquant sur un lien ou en utilisant les boutons précédent/suivant du navigateur), SvelteKit intercepte la navigation avant qu'elle ne se
```suggestion
Par défaut, lorsque vous naviguez vers une nouvelle page (en cliquant sur un lien ou en utilisant les boutons précédent/suivant du navigateur), SvelteKit intercepte la navigation avant qu'elle ne se produise et la traite lui-même plutôt que de laisser le navigateur envoyer une requête vers la page de destination. SvelteKit met ensuite à jour le contenu affiché sur le client en effectuant un rendu du composant correspondant à la nouvelle page, qui peut alors effectuer des appels vers les <span class='vo'>[endpoints](PUBLIC_SVELTE_SITE_URL/docs/web#endpoint)</span> d'<span class='vo'>[API](PUBLIC_SVELTE_SITE_URL/docs/development#api)</span> nécessaires. Ce processus de mise à jour de la page sur le client en réponse à une tentative de navigation est appelé _routing côté client_.
```

2023-11-05 20:32 UTC, Ennoriel commented on documentation/docs/60-appendix/30-glossary.md
> +Une application n'ayant qu'une seule page (_Single Page Application_, ou SPA) est une application dans laquelle toutes les requêtes vers le serveur chargent un unique fichier HTML qui s'occupe ensuit
```suggestion
Une application n'ayant qu'une seule page (_Single Page Application_, ou SPA) est une application dans laquelle toutes les requêtes vers le serveur chargent un unique fichier HTML qui s'occupe ensuite de faire le rendu côté client du contenu demandé en fonction de l'URL requêtée. Toute la navigation est gérée côté client dans un processus appelé _routing côté client_, avec le contenu spécifique à la page mis à jour et les éléments de <span class='vo'>[layout](PUBLIC_SVELTE_SITE_URL/docs/development#layout)</span> communs restant en grande partie inchangés. Les SPAs ne fournissent pas de [SSR](#ssr), ce qui a les désavantages décrits plus haut. Cependant, certaines applications ne sont pas beaucoup impactées par ces problématiques, comme une application d'entreprise nécessitant de se connecter. Dans ce cas le référencement n'est pas vraiment important, et il est admis que les utilisateurs et utilisatrices de cette application y accèdent depuis un environnement cohérent.
```

2023-11-05 20:32 UTC, Ennoriel commented on documentation/docs/60-appendix/30-glossary.md
> +La génération de site statique (_Static Site Generation_, ou SSG) est une stratégie consistant à prégénérer chaque page d'un site. SvelteKit n'a pas été conçu pour uniquement générer des sites statiq
```suggestion
La génération de site statique (_Static Site Generation_, ou SSG) est une stratégie consistant à prégénérer chaque page d'un site. SvelteKit n'a pas été conçu pour uniquement générer des sites statiques comme certains outils, et peut éventuellement être moins efficace pour prérendre un très grand nombre de pages que les outils conçus spécifiquement dans cette optique. Cependant, à l'inverse de la plupart des outils dédiés au SSG, SvelteKit permet de mélanger différents stratégies de rendu sur différentes pages. Un gros avantage à prérendre un site est que vous n'avez pas besoin de payer des serveurs pour qu'ils fassent du [SSR](#ssr). Une fois généré, le site peut être servi depuis des <span class='vo'>[CDNs](PUBLIC_SVELTE_SITE_URL/docs/web#cdn)</span>, impliquant une excellente performance du site sur l'indicateur "time to first byte". Ce modèle est généralement connu sous le nom de JAMstack.
```

2023-11-05 20:32 UTC, Ennoriel commented on documentation/docs/60-appendix/30-glossary.md
> +Le rendu côté serveur (_Server-Side Rendering_, ou SSR) est une stratégie consistant à générer le contenu d'une page sur le serveur. SSR est en général la meilleure stratégie pour le référencement. B
```suggestion
Le rendu côté serveur (_Server-Side Rendering_, ou SSR) est une stratégie consistant à générer le contenu d'une page sur le serveur. SSR est en général la meilleure stratégie pour le référencement. Bien que certains moteurs de recherche soient capables d'indexer du contenu dynamiquement généré côté client, l'indexation est en souvent plus lente dans ce cas-là, ce qui pénalise le référencement. Le SSR a également tendance à améliorer la performance perçue et rend votre application accessible aux utilisateurs et utilisatrices qui n'ont pas réussi à charger JavaScript ou si celui-ci est désactivé (ce qui arrive [plus souvent qu'on ne le croit](https://kryogenix.org/code/browser/everyonehasjs.html)).
```

2023-11-05 20:32 UTC, Ennoriel commented on documentation/docs/60-appendix/10-migrating.md
> +Supprimer `sapper` de vos `devDependencies` et remplacez-le par `@sveltejs/kit` et tout [adaptateur](adapters) que vous prévoyez d'utiliser (voir [section suivante](migrating#fichiers-de-projet-confi
```suggestion
Supprimez `sapper` de vos `devDependencies` et remplacez-le par `@sveltejs/kit` et tout [adaptateur](adapters) que vous prévoyez d'utiliser (voir [section suivante](migrating#fichiers-de-projet-configuration)).
```

2023-11-05 20:32 UTC, Ennoriel commented on documentation/docs/60-appendix/10-migrating.md
> +Supprimer `polka` ou `express` si vous les utilisez, et tout <span class='vo'>[middleware](PUBLIC_SVELTE_SITE_URL/docs/web#middleware)</span> tel que `sirv` ou `compression`.
```suggestion
Supprimez `polka` ou `express` si vous les utilisez, et tout <span class='vo'>[middleware](PUBLIC_SVELTE_SITE_URL/docs/web#middleware)</span> tel que `sirv` ou `compression`.
```

2023-11-05 20:32 UTC, Ennoriel commented on documentation/docs/60-appendix/10-migrating.md
>  Most imports from `@sapper/service-worker` have equivalents in [`$service-worker`](modules#$service-worker):
```suggestion
```

2023-11-05 20:32 UTC, Ennoriel commented on documentation/docs/60-appendix/10-migrating.md
> +Ceci a causé des problèmes et n'est donc plus le cas avec SvelteKit. À la place, les URLs relatives sont résolues par rapport à la page courante (ou la page de destination, pour les URLs `fetch`ées d
```suggestion
Ceci a causé des problèmes et n'est donc plus le cas avec SvelteKit. À la place, les URLs relatives sont résolues par rapport à la page courante (ou la page de destination, pour les URLs en argument de `fetch` dans les fonctions `load`). Dans la plupart des cas, il est plus simple d'utiliser des URLs relatives à la racine (c'est-à-dire commencant par `/`), puisque leur signification ne dépend pas du contexte.
```

2023-11-05 21:01 UTC, merged