docs: 20-10
Svelte-Society-Fr/kit pull request #5
Opened 2023-09-17 20:58 UTC by bleucitron

2023-10-04 04:19 UTC, Ennoriel requested changes

2023-10-04 04:19 UTC, Ennoriel commented on documentation/docs/20-core-concepts/10-routing.md
> +Le cœur de SvelteKit est un _routeur basé sur l'arborescence de fichiers_. Les routes de votre application — c-à-d les URLs auxquelles les utilisateurs et utilisatrices ont accès — sont définis par l
```suggestion
Le cœur de SvelteKit est un _routeur basé sur l'arborescence de fichiers_. Les routes de votre application — c'est-à-dire les URLs auxquelles les utilisateurs et utilisatrices ont accès — sont définies par les dossiers de votre projet :
```

2023-10-04 04:19 UTC, Ennoriel commented on documentation/docs/20-core-concepts/10-routing.md
> +Souvent, une page a besoin de charger de la donnée avant qu'elle puisse être rendue. Pour cela, il suffit d'ajouter un module `+page.js` qui exporte une fonction `load` :
```suggestion
Souvent, une page a besoin de charger de la donnée avant qu'elle ne puisse être rendue. Pour cela, il suffit d'ajouter un module `+page.js` qui exporte une fonction `load` :
```

2023-10-04 04:19 UTC, Ennoriel commented on documentation/docs/20-core-concepts/10-routing.md
> +Vous trouverez plus d'informations sur ces valeurs dans la section [page options](page-options).
```suggestion
Vous trouverez plus d'informations sur ces valeurs dans la section [options de page](page-options).
```

2023-10-04 04:19 UTC, Ennoriel commented on documentation/docs/20-core-concepts/10-routing.md
> +Un fichier `+page.server.js` peut exporter des _actions_. Si `load` vous permet de lire de la donnée sur le serveur, les `actions` vous permettent d'_écrire_ de la donnée sur le serveur en utilisant
```suggestion
Un fichier `+page.server.js` peut également exporter des _actions_. Si `load` vous permet de lire de la donnée sur le serveur, les `actions` vous permettent d'_écrire_ de la donnée sur le serveur en utilisant l'élément `<form>`. Pour savoir comment vous en servir, reportez-vous à la section sur les [actions de formulaire](form-actions).
```

2023-10-04 04:19 UTC, Ennoriel commented on documentation/docs/20-core-concepts/10-routing.md
> +SvekteKit "remonte l'arbre" à la recherche de la page d'erreur la plus proche — si le fichier de l'exemple ci-dessus n'existe pas, il essaie de trouver `src/routes/blog/+error.svelte` puis `src/route
```suggestion
SvekteKit "remonte l'arborescence de fichiers" à la recherche de la page d'erreur la plus proche — si le fichier de l'exemple ci-dessus n'existe pas, il essaie de trouver `src/routes/blog/+error.svelte` puis `src/routes/+error.svelte` avant d'afficher la page d'erreur par défaut. Si _cette page_ échoue également (ou si l'erreur survient au sein de la fonction `load` du `+layout` racine, qui est "au-dessus" du fichier `+error` racine), SvelteKit sauve les meubles et rend une page d'erreur statique, que vous pouvez personnaliser en créant un fichier `src/error.html`.
```

2023-10-04 04:19 UTC, Ennoriel commented on documentation/docs/20-core-concepts/10-routing.md
> +Les layouts peuvent être _imbriqués_. Supposez que nous ayons plusieurs pages `/settings`, comme `/settings/profile` et `/settings/notifications` avec un sous-menu partagé (un exemple de la vraie vie
```suggestion
Les layouts peuvent être _imbriqués_. Supposez que nous ayons plusieurs pages de paramètres : `/settings`, `/settings/profile` et `/settings/notifications` avec un sous-menu partagé (un exemple est disponible sur [github.com/settings](https://github.com/settings)).
```
j'ai rien contre la fausse vie mais je préfère enlever l'expression :p

2023-10-04 04:19 UTC, Ennoriel commented on documentation/docs/20-core-concepts/10-routing.md
> +Par défaut, chaque layout hérite du layout au-dessus de lui. Mais parfois c'est pas ce que l'on souhaite — dans ce cas, la section [layouts avancés](advanced-routing#advanced-layouts) peut vous aider
```suggestion
Par défaut, chaque layout hérite du layout au-dessus de lui. Mais parfois ce n'est pas ce que l'on souhaite — dans ce cas, la section [layouts avancés](advanced-routing#advanced-layouts) peut vous aider.
```

2023-10-04 04:19 UTC, Ennoriel commented on documentation/docs/20-core-concepts/10-routing.md
> +La donnée renvoyée d'une fonction `load` de layout est aussi accessible dans toutes ses pages enfantes :
```suggestion
La donnée renvoyée d'une fonction `load` de layout est aussi accessible dans toutes ses pages enfants :
```

2023-10-04 04:19 UTC, Ennoriel commented on documentation/docs/20-core-concepts/10-routing.md
> +	return text(`J'ai géré votre requête ${request.method} !`);
le commentaire 3 lignes au dessus est-il à traduire ? (je ne peux pas fixer de commentaire sur la ligne)

2023-10-04 11:54 UTC, Ennoriel requested changes
j'ai mis plusieurs commentaires pour traduire **des données** plutôt que **de la donnée** mais je ne l'ai pas fait partout au moins le temps que l'on se mette d'accord.

J'ai plutôt l'habitude d'entendre l'expression au pluriel même si rien n'interdit de l'écrire au singulier. Une chose que  j'aime bien à propos du singulier, c'est que dans certains paragraphes, il est possible de séparer la donnée courante des autres données mais en anglais, il n'y a que le pluriel **data** dans tous les cas

2023-10-04 11:54 UTC, Ennoriel commented on documentation/docs/20-core-concepts/20-load.md
> +Avant qu'un composant [`+page.svelte`](routing#page-page-svelte) (et son composant [`+layout.svelte`](routing#layout-layout-svelte) qui l'entoure) puisse être rendu, il est souvent nécessaire de récu
```suggestion
Avant qu'un composant [`+page.svelte`](routing#page-page-svelte) (et son composant [`+layout.svelte`](routing#layout-layout-svelte) qui l'entoure) puisse être rendu, il est souvent nécessaire de récupérer des données. Nous faisons cela avec les fonctions `load`.
```

2023-10-04 11:54 UTC, Ennoriel commented on documentation/docs/20-core-concepts/20-load.md
> +## Donnée de page
```suggestion
## Données de page
```

2023-10-04 11:54 UTC, Ennoriel commented on documentation/docs/20-core-concepts/20-load.md
> +## Donnée de layout
```suggestion
## Données de layout
```

2023-10-04 11:54 UTC, Ennoriel commented on documentation/docs/20-core-concepts/20-load.md
> +Vos fichiers `+layout.svelte` peuvent aussi charger de la donnée, via `+layout.js` ou `+layout.server.js`.
```suggestion
Vos fichiers `+layout.svelte` peuvent aussi charger des données, via `+layout.js` ou `+layout.server.js`.
```

2023-10-04 11:54 UTC, Ennoriel commented on documentation/docs/20-core-concepts/20-load.md
> +La donnée renvoyée par les fonctions `load` de <span class="vo">[layout](PUBLIC_SVELTE_SITE_URL/docs/web#layout)</span> est accessible dans le `+layout.svelte` auquel il "appartient", le composant `+
```suggestion
Les données renvoyées par les fonctions `load` de <span class="vo">[layout](PUBLIC_SVELTE_SITE_URL/docs/web#layout)</span> sont accessibles dans le fichier `+layout.svelte` auquel il "appartient", le composant `+page.svelte`, ainsi que dans les composants `+layout.svelte` enfant.
```

2023-10-04 11:54 UTC, Ennoriel commented on documentation/docs/20-core-concepts/20-load.md
> +> Si plusieurs fonctions `load` renvoient de la donnée portant la même clé, la dernière "gagne" — le résultat d'un `load` de layout renvoyant `{ a: 1, b: 2 }` et d'un `load` de page renvoyant `{ b: 3
```suggestion
> Si plusieurs fonctions `load` renvoient des données portant la même clé, la dernière "gagne" — le résultat d'un `load` de layout renvoyant `{ a: 1, b: 2 }` et d'un `load` de page renvoyant `{ b: 3, c: 4 }` serait `{ a: 1, b: 3, c: 4 }`
```

2023-10-04 11:54 UTC, Ennoriel commented on documentation/docs/20-core-concepts/20-load.md
> +Le composant `+page.svelte` et tous les composants `+layout.svelte` au-dessus ont accès à leur propre donnée en plus de toutes les données de leur parents.
```suggestion
Le composant `+page.svelte` et tous les composants `+layout.svelte` au-dessus ont accès à leurs propres données en plus de toutes les données de leur parents.
```

2023-10-04 11:54 UTC, Ennoriel commented on documentation/docs/20-core-concepts/20-load.md
> +Par défaut, les fonctions `load` universelles s'exécutent sur le serveur pendant le [SSR](glossary#ssr) lorsque l'utilisateur ou l'utilisatrice visite la page pour la première fois. Elles sont ensuit
```suggestion
Par défaut, les fonctions `load` universelles s'exécutent sur le serveur pendant le [SSR](glossary#ssr) lorsque l'utilisateur ou l'utilisatrice visite la page pour la première fois. Elles sont ensuite de nouveau exécutées lors de l'hydratation, en utilisant les réponses des [requêtes `fetch`](#requ-ter-avec-fetch). Toutes les invocations suivantes de fonctions `load` universelles ont lieu dans le navigateur. Vous pouvez personnaliser ce comportement avec les [options de page](page-options). Si vous [désactivez le rendu côté serveur](page-options#ssr), vous obtiendrez un comportement de <span class="vo">[SPA](PUBLIC_SVELTE_SITE_URL/docs/web#spa)</span>, et les fonctions `load` universelles de la page en question seront _toujours_ exécutées dans le navigateur.
```

2023-10-04 11:54 UTC, Ennoriel commented on documentation/docs/20-core-concepts/20-load.md
>  ### Input
```suggestion
### En entrée
```

2023-10-04 11:54 UTC, Ennoriel commented on documentation/docs/20-core-concepts/20-load.md
>  ### Output
```suggestion
### En sortie
```

2023-10-04 11:54 UTC, Ennoriel commented on documentation/docs/20-core-concepts/20-load.md
> +- Les requêtes internes (i.e. vers les routes `+server.js`) sont directement envoyées à la fonction concernée lorsqu'exécutées sur le serveur, sans appel HTTP supplémentaire.
```suggestion
- Les requêtes internes (i.e. vers les routes `+server.js`) exécutent directement la fonction concernée lorsqu'appelée sur le serveur, sans appel HTTP supplémentaire.
```

2023-10-04 11:54 UTC, Ennoriel commented on documentation/docs/20-core-concepts/20-load.md
> +Il est occasionnellement utile qu'une fonction `load` accède à la donnée d'une fonction `load` parente, ce qui est possible avec `await parent()` :
```suggestion
Il est occasionnellement utile qu'une fonction `load` accède à la donnée d'une fonction `load` parent, ce qui est possible avec `await parent()` :
```

2023-10-04 11:54 UTC, Ennoriel commented on documentation/docs/20-core-concepts/20-load.md
> +Lorsque qu'il rend (ou qu'il navigue vers) une page, SvelteKit exécute toutes les fonctions `load` en parallèle, en évitant une cascade de requêtes. Pendant la navigation côté client, le résultat des
```suggestion
Lorsque qu'il rend (ou qu'il navigue vers) une page, SvelteKit exécute toutes les fonctions `load` en parallèle, en évitant une cascade de requêtes. Pendant la navigation côté client, le résultat des appels de `load` serveur multiples sont groupés dans une seule et même réponse. Une fois toutes les fonctions `load` terminées, la page est rendue.
```

2023-10-04 12:05 UTC, bleucitron commented on documentation/docs/20-core-concepts/10-routing.md
> +Les layouts peuvent être _imbriqués_. Supposez que nous ayons plusieurs pages `/settings`, comme `/settings/profile` et `/settings/notifications` avec un sous-menu partagé (un exemple de la vraie vie
```suggestion
Les layouts peuvent être _imbriqués_. Supposez que nous ayons plusieurs pages de paramètres – `/settings`, `/settings/profile` et `/settings/notifications` – avec un sous-menu partagé (un exemple est disponible sur [github.com/settings](https://github.com/settings)).
```

2023-10-04 12:07 UTC, bleucitron commented on documentation/docs/20-core-concepts/10-routing.md
> +	return text(`J'ai géré votre requête ${request.method} !`);
Yep, je fais ça

2023-10-05 16:23 UTC, bleucitron commented on documentation/docs/20-core-concepts/20-load.md
>  ### Input
Je vais plutôt mettre "Paramètres d'entrée" et "de sortie"

2023-10-05 16:35 UTC, merged